name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Type of version bump.'
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GITHUB_ACTOR: ${{ github.actor }}
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      VERSION_TO_RELEASE: ${{ inputs.version }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command npm clean-install
      - run: nix develop --command npm run release:stable
